### ISSUE TITLE
Publish package on PyPI

### ISSUE THREAD

**Issue by luator** [martius-lab/smart-settings#6]
We should consider publishing this package on PyPI.  This would make it easier to specify it as a dependency for other packages.

**Comment by georgmartius** [comment]
Yes, I agree

**Comment by luator** [comment]
@georgmartius @mseitzer 

I just tagged version 1.2.0 and tried publishing to PyPI.  Unfortunately, it got rejected because the name "smart-settings" is too similar to an existing package (there is a package called "smartsettings" already).
So we need to find a different name that is sufficiently unique...

At least to my understanding, this only affects the project name (i.e. what you specify when installing), not the actual package name (that you use for importing).  I find it a bit annoying if they don't match but I'd rather not change the latter as that would break existing code.

A bit of a problem is, that we can't check of a name would be accepted beforehand, so I have to rename the project and then try uploading, until we find a name that is accepted...

Some suggestions:
- cluster-utils-smart-settings  (assuming the main use case is for use with cluster_utils)
- al-smart-settings
- martius-lab-smart-settings
- any better ideas?

**Comment by luator** [comment]
If there's no objection, I'll try "al-smart-settings", hopefully that's different enough from the existing project.

**Comment by luator** [comment]
Done: https://pypi.org/project/al-smart-settings/
